#!/bin/sh
# Installer for the agentmemoryhub macOS wake hook.
#
# - Installs sleepwatcher via Homebrew (if missing)
# - Copies wakeup.sh into ~/.agentmemoryhub (override with AGENTMEMORYHUB_HOME)
# - Writes a config file with the detected docker binary and this repo's path
# - Bridges ~/.wakeup -> the installed hook (sleepwatcher runs ~/.wakeup by default)
# - Starts sleepwatcher as a login service via `brew services`
#
# Usage:  sh scripts/install-wakeup.sh
set -e

if [ "$(uname)" != "Darwin" ]; then
  echo "error: this wake hook is macOS-only (uses sleepwatcher)." >&2
  exit 1
fi

# Resolve paths.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
AGENTMEMORYHUB_HOME="${AGENTMEMORYHUB_HOME:-$HOME/.agentmemoryhub}"

DOCKER=$(command -v docker || true)
if [ -z "$DOCKER" ]; then
  echo "error: docker not found on PATH. Install Docker Desktop first." >&2
  exit 1
fi

BREW=$(command -v brew || true)
if [ -z "$BREW" ]; then
  echo "error: Homebrew not found. Install it from https://brew.sh first." >&2
  exit 1
fi

echo "==> Installing sleepwatcher (if needed)"
if ! brew list sleepwatcher >/dev/null 2>&1; then
  brew install sleepwatcher
else
  echo "    sleepwatcher already installed."
fi

echo "==> Setting up $AGENTMEMORYHUB_HOME"
mkdir -p "$AGENTMEMORYHUB_HOME"
cp "$SCRIPT_DIR/wakeup.sh" "$AGENTMEMORYHUB_HOME/wakeup.sh"
chmod +x "$AGENTMEMORYHUB_HOME/wakeup.sh"

cat > "$AGENTMEMORYHUB_HOME/config" <<EOF
# Generated by install-wakeup.sh on $(date)
PROJECT_DIR="$REPO_DIR"
DOCKER="$DOCKER"
LOG="$AGENTMEMORYHUB_HOME/wakeup.log"
EOF
echo "    wrote $AGENTMEMORYHUB_HOME/config (PROJECT_DIR=$REPO_DIR)"

# sleepwatcher (via brew services) runs ~/.wakeup. Bridge it to our hook.
WAKEUP_BRIDGE="$HOME/.wakeup"
HOOK_CALL="\"$AGENTMEMORYHUB_HOME/wakeup.sh\"  # agentmemoryhub wake hook"
if grep -q "agentmemoryhub wake hook" "$WAKEUP_BRIDGE" 2>/dev/null; then
  echo "==> ~/.wakeup already calls the agentmemoryhub hook — leaving it as is"
elif [ -f "$WAKEUP_BRIDGE" ]; then
  echo "==> Existing ~/.wakeup found — appending agentmemoryhub hook"
  printf '\n%s\n' "$HOOK_CALL" >> "$WAKEUP_BRIDGE"
else
  echo "==> Writing ~/.wakeup bridge"
  printf '#!/bin/sh\n%s\n' "$HOOK_CALL" > "$WAKEUP_BRIDGE"
fi
chmod +x "$WAKEUP_BRIDGE"

echo "==> Starting sleepwatcher service"
brew services restart sleepwatcher

echo ""
echo "Done. The agentmemory tunnel will restart automatically on wake."
echo "  hook:   $AGENTMEMORYHUB_HOME/wakeup.sh"
echo "  config: $AGENTMEMORYHUB_HOME/config"
echo "  log:    $AGENTMEMORYHUB_HOME/wakeup.log"
echo ""
echo "Test it: close the lid for a minute, reopen, then:"
echo "  cat $AGENTMEMORYHUB_HOME/wakeup.log"
